# __Intro A TensorFlow__

In [1]:
import tensorflow as tf

## Revisando Versiones

In [2]:
print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 2.14.0


## Primeros Tensors

In [3]:
scalar_tensor = tf.constant(7)
scalar_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
tensor_vector = tf.constant([1, 2, 3])
tensor_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
tensor_matrix = tf.constant([[1, 2], [3, 4]])
tensor_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

## __OBS: Recordar Que Estamos Trabajando Con Tensors, Podemos Transformarlos A Numpy Arrays__

In [7]:
tensor_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [8]:
tensor_vector.numpy()

array([1, 2, 3])

## Operaciones

In [9]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([4, 5, 6])

In [11]:
t2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [12]:
suma = tf.add(t1, t2)
suma

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [13]:
resta = tf.subtract(t1, t2)
resta

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [14]:
multiplicacion = tf.multiply(t1, t2)
multiplicacion

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [15]:
division = tf.divide(t1, t2)
division

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

## Slicing

In [16]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [17]:
primera_fila = tensor[0, :]
primera_fila

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
segunda_columna = tensor[: , 1]
segunda_columna

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8])>

In [19]:
sub_matriz = tensor[:2, :2]
sub_matriz

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

## Reshaping

In [20]:
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [21]:
tensor_reshaped = tf.reshape(tensor, (1, 9))
tensor_reshaped

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])>

## La Importancia De Las Dimensiones

In [22]:
x = tf.constant([1, 2, 3])
y = tf.constant([[1], [2], [3]])

In [23]:
x.shape , y.shape

(TensorShape([3]), TensorShape([3, 1]))

In [24]:
tf.add(x, y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>

In [ ]:
.